- hosts: all
  become: true
  vars_files:
    - defaults/main.yml
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  tasks:
    - name: Fix my DNS
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 1.1.1.1"

    - import_tasks: tasks/main.yml