- name: Deploy sample app
  kubernetes.core.helm:
    name: httpbin
    chart_repo_url: https://matheusfm.dev/charts
    chart_ref: httpbin
    chart_version: 0.1.1
    release_namespace: httpbin
    create_namespace: true
    #state: absent
    values:
      service:
        type: NodePort
        port: 80
        nodePort: 30091

- name: Get pods info
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    label_selectors:
      - "app.kubernetes.io/instance=httpbin"
    namespace: httpbin
    wait_sleep: 10
    wait_timeout: 360
  register: _httpbin