---
- import_tasks: microshift.yml
  tags: microshift

- include_role:
    name: gantsign.helm

- name: Confirm k8s is running
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    label_selectors:
      - "dns.operator.openshift.io/daemonset-dns=default"
    namespace: openshift-dns
    wait_sleep: 1
    wait_timeout: 360

- import_tasks: dns.yml
  tags: dns

# - import_tasks: metallb.yml
#   tags: metallb

- import_tasks: console.yml
  tags: console

# - import_tasks: helm.yml
#   tags: helm

- import_tasks: argocd.yml
  tags: argocd

- import_tasks: argocd_apps.yml
  tags: argocd_apps

...