---
- name: Deploy metallb
  kubernetes.core.helm:
    name: metallb
    chart_repo_url: https://metallb.github.io/metallb
    chart_ref: metallb
    release_namespace: metallb-system
    wait: true
    create_namespace: true

- name: Confirm metallb is running
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    label_selectors:
      - "app.kubernetes.io/instance=metallb"
    namespace: metallb-system
    wait_sleep: 10
    wait_timeout: 120

- name: Get an existing Service object
  kubernetes.core.k8s:
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: first-pool
        namespace: metallb-system
      spec:
        addresses:
        - 192.168.56.100-192.168.56.110
...